### ISSUE TITLE
Create an Index example in user guide does not compile with Specs2 5.5.3

### ISSUE THREAD

**Issue by phdoerfler** [etorreborre/specs2#1275]
This code snippet in the user guide: https://etorreborre.github.io/specs2/guide/SPECS2-5.2.0/org.specs2.guide.HtmlOutput.html#create-an-index:

```scala
import org.specs2.*
import specification.core.*
import runner.SpecificationsFinder.default.*

class index extends Specification:
  def is =
    examplesLinks("Example specifications")

  // see the SpecificationsFinder trait for the parameters of the 'specifications' method
  def examplesLinks(t: String) =
    t.title ^
      Fragments.foreach(specifications())(s => link(s) ^ br)
```

does not compile with specs2 5.5.3:

```
[error] -- [E008] Not Found Error: /work/space/CompressionPlayground/src/test/scala/index.scala:3:35 
[error] 3 |import runner.SpecificationsFinder.default.*
[error]   |       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[error]   |value default is not a member of object org.specs2.runner.SpecificationsFinder, but could be made available as an extension method.
[error]   |
[error]   |One of the following imports might make progress towards fixing the problem:
[error]   |
[error]   |  import org.specs2.specification.Forms.asExecutionIsInterpolated
[error]   |  import org.specs2.specification.Forms.asResultIsInterpolated
[error]   |
[error] one error found
[error] (Test / compileIncremental) Compilation failed
[error] Total time: 1 s, completed Oct 10, 2024 1:38:40 PM
```
A possible albeit ugly solution is this code:

```scala
import org.specs2.*
import specification.core.*
import runner.SpecificationsFinder

class index extends Specification:
  def is =
    examplesLinks("Example specifications")

  // see the SpecificationsFinder trait for the parameters of the 'specifications' method
  def examplesLinks(t: String) =
    t.title ^
      Fragments.foreach(SpecificationsFinder.create(Env()).specifications())(s => link(s) ^ br)
```

**Comment by etorreborre** [comment]
Thanks @phdoerfler for reporting this. The example [has actually been updated in a more recent version of specs2](https://github.com/etorreborre/specs2/blob/a5c8f1016bd2a11268c857097b7f0d992da2b645/guide/src/test/scala/org/specs2/guide/HtmlOutput.scala#L85). 

What your issue tells me is that the CI action for publishing the docs stopped working at some stage. I'm going to look into this.

**Comment by etorreborre** [comment]
This is now fixed [here](https://etorreborre.github.io/specs2/guide/SPECS2-5.5.6/org.specs2.guide.HtmlOutput.html#create-an-index).
