### ISSUE TITLE
Integration with scalacheck in 2.9.0_1-1.3

### ISSUE THREAD

**Issue by omj** [etorreborre/specs2#19]
Before moving to 2.9.0-1-1.3 I used 2.8.1_1.6.7. My test code with specs and scalacheck looked like this: 

object MySpec extends Specification with ScalaCheck {

  val generator:Gen[String] = Gen{
     prms =>
    Some("this is stub implementation of generator")
  }

  "my spec" should{
     "check something" in{
       generator must pass{
         str => str must beEqualTo ("this is stub implementation of generator")
       }
     }
   }
}

After migrating to 2.9.0_1-1.3 I got compilation errors like this:  MySpec.scala:17: not found: value pass
