### ISSUE TITLE
Mockito problems with Scala 2.11

### ISSUE THREAD

**Issue by zygm0nt** [etorreborre/specs2#484]
Hi

I have a couple lines of code in my test, which does not compile with specs2 (versions 2.4.1 and 3.8.3) and scala 2.11. 

The first snippet is 

```
"log error message when Cassandra DAO fails" in {
      // given
      cassandraDAO.findById(...) returns Future.failed(new RuntimeException("cassandra offline"))

      // when & then
      Get("/probe") ~> probeService.route(StatusCodes.OK, "OK") ~> check {
        there was one(probeServiceLogger).error(===("Probe failed"), any[RuntimeException])
      }
    }
```

The second looks like this:

```
"timeout if underlying Future doesn't complete" in new Context {
      // given
      val future = Promise[String]().future

      // when
      val sealedFuture = seal(future, "future description")

      // then
      eventually {
        sealedFuture.value.get.failed.get must beAnInstanceOf[TimeoutException]
        there was one(logger).error(===("Timeout after 1000ms while waiting for future description"), any[TimeoutException])
      }
    }
```

The compiler error is always like this:

```
[error]  found   : => Any
[error]  required: Object
[error] Note that <byname> extends Any, not AnyRef.
[error] Such types can participate in value classes, but instances
[error] cannot appear in singleton types or in reference comparisons.
[error]       Get("/probe") ~> probeService.route(StatusCodes.OK, "OK") ~> check {
[error]                                                                 ^
```

But commenting the Mockito lines fixes compilation errors. So this does not seem to be spray-specs2 interoperability, but rather Mockito-specs2.

This code worked with specs2 version 2.4.1 and scala 2.10.

Is this some kind of a known problem? If you'd need more information about my setup I'll try to update this issue.

**Comment by etorreborre** [comment]
I am sorry I tried different things but I really can not reproduce your issue. Can you create a small example where I can reproduce it?

**Comment by etorreborre** [comment]
@zygm0nt any news?

**Comment by zygm0nt** [comment]
Hi, I'll try to extract this into a separate project tomorrow. Sorry, today we had a day off.

**Comment by zygm0nt** [comment]
I've extracted the problem into this repo: https://github.com/zygm0nt/specs2-mockito-example 

Running SealedFutureSpec results in compilation error.

**Comment by etorreborre** [comment]
I don't know exactly why there is an issue there but I know how to fix it thanks to your example repo:
```
there was one(logger).error(argThat(===("Timeout")), any[TimeoutException])
```

**Comment by zygm0nt** [comment]
Works great. Thanks for your help!
