### ISSUE TITLE
Migrate JSON matchers from Scala 2.11 + Specs 2.3.11 to Scala 2.12 + Specs 2.4.17

### ISSUE THREAD

**Issue by noahlz** [etorreborre/specs2#553]
I'm attempting to upgrade salat/salat to Scala 2.12 and therefore Specs2 2.4.17.  

Old version: Scala 2.11.8 / Specs2 2.3.11

Upon upgrade, one of the project tests gets the following compilation error:

For code:

```
          val json = """{ "ints" : [1, 2, 3], "strings" : ["a", "b", "c"] }"""
          rendered must /("ints" -> JSONArray(ints))
          rendered must /("strings" -> JSONArray(strings))
```

Error:

```

[error]  found   : (String, scala.util.parsing.json.JSONArray)
[error]  required: JsonSpec.this.JsonSelector
[error]           rendered must /("ints" -> JSONArray(ints))
[error]                                  ^

[error]  found   : (String, scala.util.parsing.json.JSONArray)
[error]  required: JsonSpec.this.JsonSelector
[error]           rendered must /("strings" -> JSONArray(strings))
[error]                                     ^
[error] two errors found
```

What is the correct combination of imports / type parameters to make this compile?

**Comment by noahlz** [comment]
Also: I'm hitting this issue again:

`org.scalaz.stream#scalaz-stream_2.11;0.5a: not found` 

When I try to cross build with Scala 2.11.8 and Specs2 2.4.17

**Comment by etorreborre** [comment]
Hi @noahlz, the syntax would now be
```scala
import org.specs2.matcher._

json must /("ints").andHave(===(JsonArray(List(1, 2, 3))))
```

About `org.scalaz.stream#scalaz-stream_2.11;0.5a: not found` do you have `"scalaz-bintray" at "http://dl.bintray.com/scalaz/releases"` in your resolvers?

Also why not try to upgrade salat to specs2 `3.8.8` directly?

**Comment by etorreborre** [comment]
Also I am not a great fan of those json matchers anyway. I am now wondering that we could get a much nicer support by using the recently introduced `Diffable` typeclass to get a nice display of differences in a json document.

**Comment by etorreborre** [comment]
@noahlz any progress on this issue?

**Comment by noahlz** [comment]
No, but let's close for now. 

We're not going to upgrade salat to 2.12.x at this time, so that will simplify things.

**Comment by etorreborre** [comment]
Ok, please re-open an issue when you tackle this again.
