### ISSUE TITLE
java.lang.NoSuchMethodError: org.specs2.mock.mockito.CalledMatchers.checkResultFailure

### ISSUE THREAD

**Issue by zachncst** [etorreborre/specs2#560]
Hi, I'm running into an error after upgrading to 3.8.6-scalaz-7.1, when I'm calling `andThen` (Mockito) I'm seeing this exception:

```
java.lang.NoSuchMethodError: org.specs2.mock.mockito.CalledMatchers.checkResultFailure(Lorg/specs2/execute/Result;)Lorg/specs2/execute/Result;
	at org.specs2.mock.mockito.CalledMatchers$ToInOrderMode.andThen(CalledMatchers.scala:158)
	at co.adhoclabs.business_service.managers.VerifyCodeManagerTest$$anonfun$11$$anonfun$apply$22$$anonfun$apply$28.apply(VerifyCodeManagerTest.scala:158)
	at co.adhoclabs.business_service.managers.VerifyCodeManagerTest$$anonfun$11$$anonfun$apply$22$$anonfun$apply$28.apply(VerifyCodeManagerTest.scala:156)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:236)
	at scala.util.Try$.apply(Try.scala:191)
	at scala.util.Success.map(Try.scala:236)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.processBatch$1(BatchingExecutor.scala:67)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:82)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at akka.dispatch.BatchingExecutor$Batch$$anonfun$run$1.apply(BatchingExecutor.scala:59)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
	at akka.dispatch.BatchingExecutor$Batch.run(BatchingExecutor.scala:58)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:41)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:393)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

My test is just using Specification with Mockito. Not doing anything fancy. The tests are running a future and I'm calling await but I've tried the mock in and outside the Future. Any help would be appreciated.

**Comment by etorreborre** [comment]
Can you run `sbt> show test:externalDependencies` and `sbt>show evicted`. You either need:

 - to clean compile (sometimes incremental compilation fails to recompile properly after changing dependencies)
 - upgrade another library. For example you might have updated `specs2-core` but not `specs2-mockito`

**Comment by zachncst** [comment]
I knew it was something simple but I had ran out of patience trying to debug it. We upgraded from a really old version, and didn't have the `spec2-mock` dependency even in our list. Once I added it, the error was resolved. Thanks!

**Comment by etorreborre** [comment]
Good :-).
